apiVersion: apps/v1
kind: Deployment 
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: app-server
          image: nginx
          ports:
            - port: 80
              containerPort: 80
      imagePullSecrets:
        - name: regcred      